build:
    image: fedora:latest
    script:
      - pwd 
      - ls -a
      - time dnf update -y
      - time dnf install firefox nodejs npm yarnpkg -y
      - time yarn
      - time yarn run build

test:
    image: fedora:latest
    script:
      - pwd 
      - ls -a
      - time dnf update -y
      - time dnf install firefox nodejs npm yarnpkg -y
      - time yarn
      - time yarn run test
  